### ISSUE TITLE
compute coverage around target body like deeptools scale-regions mode？

### ISSUE THREAD

**Issue by junjunlab** [js2264/tidyCoverage#1]
Hi，thanks for this great tool. Can tidyCoverage computes signals around target feature body like deeptools computeMatrix function scale-regions mode?

**Comment by js2264** [comment]
Hi @junjunlab, thanks for getting in touch. I am not planning on adding this feature to `tidyCoverage` in the short term. Perhaps in the longer term, but for now I have other priorities. I'd be happy to review PRs though!
